### PR TITLE
preexec: set options before load

### PR DESCRIPTION
**Pull request by gaelicWizard**
## Description
By setting `__bp_delay_install`, we avoid any immediate initialization at all. We then override two troublesome functions before calling `__bp_install_after_session_init()`.

The `__bp_install_after_session_init()` function doesn't enable the DEBUG trap, just sets `$PROMPT_COMMAND` to include `__bp_install()`, so the actual final `$PROMPT_COMMAND` is not finished, and DEBUG trap set, until after the first prompt is displayed.

## Motivation and Context
Along with upstream PR 119, this should make things safe and reliable to use.

## How Has This Been Tested?
A variation of this is live on my main branch.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
@gaelicWizard I tested this, but didn't include your changes to the preexec lib. With your `init.d` modifications in place, it seems like everything works as expected. At this point, I think you should close this PR and open one directly on the core bash-it repo to modify `bash_it.sh` and `vendor/init.d/preexec.bash`.

Edit: to be clear, I don't think we should wait on rcaloras/bash-preexec#119. from my testing, what you've figured out works with preexec as-is.

**Comment by gaelicWizard** [comment]
The problem is that without some changes to upstream, the "current" command passed in to the preexec function(s) may be inaccurate.

**Comment by cornfeedhobo** [comment]
Well, the preexec owner has been very polite and pretty clear that they aren't going to merge any of our PRs. The fact that iTerm ships with a patched version of `preexec` puts a lot of weight on the pattern of end-users working around any `preexec` issues. I think we have to accept this reality and find a way forward on our own.

Within that context, let me know if you have any other clever ideas. I'll try to think about this at my next free iteration cycle.

**Comment by gaelicWizard** [comment]
I'm just butt-hurt that (after being grumpy) I put in the work to fix their code to do *everything* they wanted, add emulation of user-configured preference while still doing their mangling (from another patch), *and* fall back to `$BASH_COMMAND` when `$HISTCONTROL` is read-only preventing their mangling, **and** added your compatibility for Bash 3.2+, and they just DGAF. 

Like, I get it they dude just wants to do his thing but...like my combined patch *does* do his thing and alsö our thing. 😢 #sadpanda 

(I drink the open source cool-aid; I always imagine that everyone is altruistic and out to help each other (within reason), &c, &c.)

And on top of that, once I realized same dude alsö runs BashHub, I realized that actually that's kinda cool and makes total sense why he wants to make sure history entries don't silently disappear, *but* *alsö* it's extremely creepy that a no-security cloud sync service goes out of it's way to silently and without documentation alter a user-configured setting which many users rely* on to hide passwords from their shell history file. Like, literally I would specifically want to hide *some* history from the automatic cloud sync service.

* It's is not a good feature to rely on security-wise, but that doesn't change reality that people do.

Anyway, enough whining. 😃

**Comment by cornfeedhobo** [comment]
@gaelicWizard Yeah, I think that's where we see projects get forked. You could always start `bash-preexec-ng` or something

**Pull request closed without merging**
